config/routes.rb
Rails.application.routes.draw do
  resources :todo_items
  root 'todo_items#index'

end

app/models/todo_item.rb
class TodoItem < ActiveRecord::Base
  validates :description, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :set_todo_item, only: [:show, :edit, :update, :destroy]

  # GET /todo_items
  # GET /todo_items.json
  def index
    @todo_items = TodoItem.all
  end

  # GET /todo_items/1
  # GET /todo_items/1.json
  def show
  end

  # GET /todo_items/new
  def new
    @todo_item = TodoItem.new
  end

  # GET /todo_items/1/edit
  def edit
  end

  # POST /todo_items
  # POST /todo_items.json
  def create
    @todo_item = TodoItem.new(todo_item_params)

    respond_to do |format|
      if @todo_item.save
        format.html { redirect_to root_path, notice: 'Todo item was successfully created.' }
        format.json { render :show, status: :created, location: @todo_item }
      else
        format.html { render :new }
        format.json { render json: @todo_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_items/1
  # PATCH/PUT /todo_items/1.json
  def update
    respond_to do |format|
      if @todo_item.update(todo_item_params)
        format.html { redirect_to root_path, notice: 'Todo item was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_item }
      else
        format.html { render :edit }
        format.json { render json: @todo_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_items/1
  # DELETE /todo_items/1.json
  def destroy
    @todo_item.destroy
    respond_to do |format|
      format.html { redirect_to todo_items_url, notice: 'Todo item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_item
      @todo_item = TodoItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_item_params
      params.require(:todo_item).permit(:description, :star, :check)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>To Do List</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
	<link href='//fonts.googleapis.com/css?family=Arvo:400,700' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
	<link href='//fonts.googleapis.com/css?family=Indie+Flower' rel='stylesheet' type='text/css'>
</head>

<body>

<%= yield %>

</body>
</html>

app/views/todo_items/_form.html.erb
<%= form_for(@todo_item) do |f| %>
  <% if @todo_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo_item.errors.count, "error") %> prohibited this todo_item from being saved:</h2>

      <ul>
      <% @todo_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description, placeholder: "What to do?" %>
  </div>
  <div class="field">
    <%= f.label :star %><br>
    <%= f.check_box :star %>
  </div>
  <div class="field">
    <%= f.label :check %><br>
    <%= f.check_box :check %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todo_items/edit.html.erb
<div class="todo_panel">
	<header>Edit Todo Item</header>

	<div class="todo_form">
	<%= render 'form' %>
	<%= link_to 'Home', todo_items_path, class: 'todo_link' %>
	</div>
</div>

app/views/todo_items/index.html.erb
<!-- <div class="header">
  <h1>To Do List</h1>
</div>
<div class="main">
  <div class="list">
  </div>
  <form class="form">
    <div class="form-container">
      <input id="todo" type="text" class="form-input" placeholder="What to do?">
    </div>
    <button type="submit" class="btn">+Add to list</button>
  </form>
</div>
 -->


<div class="todo_panel">
  <header>To Do List</header>

  <section>
    <p id="notice"><%= notice %></p>

    <% @todo_items.each do |todo_item| %>
      <% completed = "" %>
      <% striked = "" %>
      <% glow = "" %>

      <% if todo_item[:check] == true %>
        <% completed = "complete" %>
        <% striked = "striked" %>
      <% end %>

      <% if todo_item[:star] == true %>
        <% glow = "glow" %>
      <% end %>

      <div class="wrapper">
        <div class="left">
          <div class="item">
            <i class="<%= completed %> fa fa-check"></i>
          </div>
          <div class="item">
              <i class="<%= completed %> <%= glow %> fa fa-star"></i>
          </div>
        </div>

        <div class="item">
          <p class="<%= completed %> <%= striked %>">
            <%= todo_item.description %>
          </p>
        </div>

        <div class="right">
          <div class="item">
            <p class="<%= completed %>">
              <%= link_to 'Edit', edit_todo_item_path(todo_item), class: 'todo_link'%>
            </p>
          </div>
          <div class="item">
            <%= link_to todo_item, class: 'todo_link', method: :delete, data: { confirm: 'Are you sure?' } do %>
              <i class="<%= completed %> todo_link fa fa-trash"></i>
            <% end %>
          </div>
        </div>

      </div>
    <% end %>
  </section>

  <div class="todo_link">
    <%= link_to 'New To Do Item', new_todo_item_path, class: 'todo_link' %>
  </div>
</div>

app/views/todo_items/new.html.erb
<div class="todo_panel">
	<header>New To Do Item</header>

	<div class="todo_form">
		<%= render 'form' %>
		<%= link_to 'Home', todo_items_path, class: 'todo_link' %>
	</div>
</div>

app/views/todo_items/show.html.erb
<p id="notice"><%= notice %></p>
	<p>
  <strong>Description:</strong>
	  <%= @todo_item.description %>
	</p>

	<p>
	  <strong>Star:</strong>
	  <%= @todo_item.star %>
	</p>

	<p>
	  <strong>Complete?</strong>
	  <%= @todo_item.check %>
	</p>

<div class="links">
	<%= link_to 'Edit', edit_todo_item_path(@todo_item) %> |
	<%= link_to 'Destroy', todo_item_path(@todo_item), method: :delete, data: { confirm: 'Are you sure?' } %> |
	<%= link_to 'Back', todo_items_path %>
</div>